version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: cigar
      POSTGRES_PASSWORD: cigar
      POSTGRES_DB: cigar
    restart: always
    networks:
      - cigar-recipes
networks:
  cigar-recipes:
